version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_DEBUG=1
    restart: unless-stopped

  sql_db:
    image: mysql:latest
    container_name: sql_db
    ports:
      - "8000:3306"
    volumes:
      - sql_db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Secret_PW
      - MYSQL_DATABASE=Conversation_Storage
    restart: unless-stopped
volumes:
  ollama_data:
  sql_db_data:
